steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tidal-mote-440113-g9/demo-app', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tidal-mote-440113-g9/demo-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'demo-app-v1',
           '--image', 'gcr.io/tidal-mote-440113-g9/demo-app',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated'
    ]
images:
  - 'gcr.io/tidal-mote-440113-g9/demo-app'